### ISSUE TITLE
Integrate usage of Splunkbase API

### ISSUE THREAD

**Issue by edro15** [splunk/Splunk-Apps-Deployment-Architecture#62]
This is to keep `deployment.yml` user-friendly and to the bare minimum by automating fetching of specific splunkbase apps data.

Edit `splunkbase-apps` format in `deployment.yml`:
* The app name should match the app title, which is the one shown in Splunkbase (e.g. "TA for Tenable" would become "Tenable Add-On for Splunk" as per [Splunkbase](https://splunkbase.splunk.com/app/4060))
* Remove `app_id` and `license`

```yml
# `deployment.yml` example
target:
  url: <your URL>
apps:
  Splunk_TA_app1:
    s3-bucket: splunk-apps-deployment
    source: apps/Splunk_TA_app1.tgz
    config:
      - ./Splunk_TA_app1/*.conf
splunkbase-apps:
  Tenable Add-On for Splunk:
    version: 7.0.0
  Splunk Add on for Microsoft Azure:
    version: 4.2.0
```

Modify `deploy.py` to:
* Extract `uid` (or appid), `license` and eventually `appid` (or app_name) via [Splunkbase API](https://splunk.atlassian.net/wiki/spaces/PROD/pages/313538955655/Splunkbase+API+v1+Documentation)

```bash
# Example to get data for the Tenable TA"
curl --location --request GET 'https://splunkbase.splunk.com/api/v1/app?limit=1&query=%22Tenable%20Add-On%20for%20Splunk%22'
```

Update [documentation](https://github.com/splunk/Splunk-Apps-Deployment-Architecture/blob/main/README.md) accordingly
